# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('priority', models.IntegerField(choices=[(1, 'Urgent'), (2, 'Pressing'), (3, 'Not Urgent'), (4, 'If you have nothing else to do')], default=2)),
                ('status', models.IntegerField(choices=[(1, 'backglog'), (2, 'ready'), (3, 'doing'), (4, 'done')], default=1)),
                ('description', models.TextField()),
            ],
        ),
    ]
