# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 22:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_auth_u'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='auth_u',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
